### ISSUE TITLE
台服数据档线报错

### ISSUE THREAD

**Issue by xiaobailoves** [assassingyk/bandori-predict#7]
聊天记录,插件报错消息:

Diamond Alone. 19:18:39
邦邦档线 500

小仓唯 19:18:42
当前活动：175期，怪盜HelloHappy與另一人怪盜

小仓唯 19:18:42
正在预测，请稍候……

小仓唯 19:18:51
预测结束，正在生成结果……

小仓唯 19:18:58
生成失败……Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/modules/bandori_predict/GraphDraw.py", line 267, in main
    (pctList, ptList, slpList, ufinList, finList, bfinList, predPct)=dataTrans(eventNumber,areacode,eventNumber,rankType)
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/modules/bandori_predict/__init__.py", line 95, in bang_predict
    GraphDraw.GetDataPic(areacode,imgbasePath,basePath,False,enum,RankType=ranktype)   #use file to Pic
  File "/root/HoshinoBot/hoshino/modules/bandori_predict/GraphDraw.py", line 294, in GetDataPic
    main(Benum,RankType,areacode,basePath,JsonPath)
  File "/root/HoshinoBot/hoshino/modules/bandori_predict/GraphDraw.py", line 274, in main
    noptHandle(eventName,basePath,rankType)
  File "/root/HoshinoBot/hoshino/modules/bandori_predict/GraphDraw.py", line 85, in noptHandle
    filename=basePath+flist[rankType]
IndexError: list index out of range

国服测试无报错,为何台服就会这样？
测试过别人的bot,也会出现这样的报错,且发现bd.json event.json文件除了t1之外,都无法正常生成在对应文件夹中.
尝试过反代bestdori.com,但是发现并不是api的问题
求解决,感谢

**Comment by assassingyk** [comment]
我这边测试的只有2k档线出现了这个问题，100-1k的档线都可以正常出结果……应该是besdori提供的报点数据源本身格式出了问题吧，插件这边恐怕没什么可做的）
![image](https://user-images.githubusercontent.com/55473115/173765456-c863d0bd-d6eb-40b5-b973-54fec6e73aeb.png)
![image](https://user-images.githubusercontent.com/55473115/173765603-ce0f48a9-ce2c-45d4-a19a-466bdccb51eb.png)
![image](https://user-images.githubusercontent.com/55473115/173765638-7ba982ee-cd82-4f45-b248-0f6d64ab7587.png)
![image](https://user-images.githubusercontent.com/55473115/173765671-d106a860-3107-40ce-8620-c17b8df8fd3d.png)

**Comment by assassingyk** [comment]
看了一下台服1k和2k都没有人报点，但是noptHandle正常应该像1k那样返回一个报点过少的提示图才对，应该还是这步有点问题
![image](https://user-images.githubusercontent.com/55473115/173767092-571ece56-411c-4d5f-87ac-da3d13cf5633.png)

**Comment by assassingyk** [comment]
看来本质问题是不同服务器besdori提供的可用档线档位不一样，国服是50,100,300,500,1k,2k，台服就只提供100和500的数据了，预测其他档线自然是空的……目前设置的不加参数默认预测1k线，如果主玩台服建议修改下默认预测的档线
